name: Testing with github actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup docker
      uses: docker://python:3.9.2-alpine3.13

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Unit test
      run: |
        pytest -vvv
