name: Testing with github actions

on: [push]

jobs:
  build:

    runs-on: python:3.9.2-alpine3.13

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Unit test
      run: |
        pytest -vvv
