name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: docker://python:3.9.2-alpine3.13

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Unit test
      run: |
        pytest -vvv

    - name: Creating badges
      uses: emibcn/badge-action@v1
      with:
        label: 'Test coverage'
        status: '53.4%'
        color: 'blue,555,daf'
        path: '.github/badges/coverage.svg'
